### ISSUE TITLE
Alert can handle multiple remediations

### ISSUE THREAD

**Issue by ChrisMacNaughton** [ChrisMacNaughton/Mjolnir#39]
An alert should be able to trigger multiple remediations, in one of three styles:

1. All remediations are handled in parallel
2. The remediations are handled in order
3. The remediations are handled in order, and processing is stopped by a successful remediation

All three of these could be handled, given the correct configuration language

**Comment by cholcombe973** [comment]
I'm not sure what situation would call for a parallel remediation

**Comment by ChrisMacNaughton** [comment]
I'm not certain of a good use for parallel but it shouldn't be that hard, and could be limited, think parallel iterator with three workers.

**Comment by ChrisMacNaughton** [comment]
An alert is currently allowed to have multiple remediation handlers, and they are called in serial until one of them is successful
